version: "2"
services:
  rake:
    entrypoint: bundle exec rake
    build:
      context: .
    environment:
      - RAILS_ENV=test
      - RACK_ENV=test
    volumes:
      - .:/app
  
  bump:
    build:
      context: .
    entrypoint: gem release #bump -p -t -v
    volumes:
      - .:/app
      - ~/.gitconfig:/nonexistent/.gitconfig
      - ~/.ssh:/nonexistent/.ssh