version: "2"
services:
  rake:
    entrypoint: bundle exec rake
    build:
      context: .
    environment:
      - RAILS_ENV=test
      - RACK_ENV=test
    volumes:
      - .:/app
  
  gem:
    build:
      context: .
    entrypoint: gem
    volumes:
      - .:/app
      - ~/.gitconfig:/nonexistent/.gitconfig
      - ~/.ssh:/nonexistent/.ssh
      - ~/.gem:/nonexistent/.gem