version: 2
jobs:
  build:
    working_directory: ~/blinkist/blinkist-config
    parallelism: 1
    docker:
    - image: circleci/ruby:2.3.6-node-browsers
    steps:
    - checkout
    - run: 
        name: Bundle Install
        command: bundle install --jobs=4 --retry=3 --path=vendor/bundle
    - run:
        name: RSpec
        command: bundle exec rspec --format progress spec
        environment:
          RAILS_ENV: test
          RACK_ENV: test
